### PR TITLE
fix: always send filename in content-disposition headers

### LINKED ISSUE #125: Part exceeded maximum size of 1024KB
# Problem

When trying to upload a JPG file I'm encountering invalid_request_error: "Part exceeded maximum size of 1024KB."

~~It looks like this gem is setting the media-type to "multipart/form-data" as expected, but then submitting `file` as a string parameter instead of a file upload.~~ UPDATE: The problem was this gem was setting an invalid `Content-Disposition` part header so servers were __parsing__ the `file` param as a string instead of a file upload.

# Details

- Claude API documentation [says](https://docs.anthropic.com/en/docs/build-with-claude/files#file-storage-and-limits) "Maximum file size: 500 MB per file".
- My file is 1.1MB
- A web search indicates this error message "Part exceeded maximum size of 1024KB" originates from Starlette, so I assume the Claude API uses Starlette.
- Can replicate with both String and StringIO values for `file`.
- Can replicate this error across multiple environments (development and production).
- Can replicate with and without [shorter multipart boundaries](https://github.com/anthropics/anthropic-sdk-ruby/pull/124).
- Cannot replicate with cURL, meaning the problem seems to be with how this gem is sending requests.
- This is NOT a problem with extra headers like `betas: "anthropic-beta"` or params like `beta=true`.

# Code

```
anthropic = Anthropic::Client.new
file_string = File.read('/some/path/file.jpg')
anthropic.beta.files.upload(file: file_string)

Anthropic::Errors::BadRequestError
{
  :url=>"https://api.anthropic.com/v1/files?beta=true",
  :status=>400, 
  :body=>{
    :type=>"error", 
    :error=>{
      :type=>"invalid_request_error", 
      :message=>"Part exceeded maximum size of 1024KB."
    }, 
    :request_id=>"req_011CSoyEPUAzWgTzPoJfESpt"
  }
}
```

### PR DESCRIPTION
**Pull request by dan-jensen**
# Problem

File uploads were raising `Anthropic::Errors::BadRequestError` because the Anthropic API was returning a 400 response with the message ["Part exceeded maximum size of 1024KB"](https://github.com/anthropics/anthropic-sdk-ruby/issues/125). That was because this gem was sending Content-Disposition part headers without a "filename" parameter. Although that parameter is not required by RFC, it is required by many servers like Starlette (Anthropic) and Rack.

# Resolution

This changes Content-Disposition header generation so a "filename" parameter is always given. This is what solves the file upload problem.

This also ensures a "name" parameter is always given, because [RFC 7578](https://datatracker.ietf.org/doc/html/rfc7578) requires it for the Content-Disposition header to be valid. ("The Content-Disposition header field MUST also contain an additional parameter of "name"".)

This resolves #125.

### CODE REVIEW

**Comment by ms-jpq** [comment]
hi @dan-jensen,

you are absolutely right in that we should do a better job making sure the file uploading API harder to mis-use. 

Currently this is documented under https://github.com/anthropics/anthropic-sdk-ruby?tab=readme-ov-file#file-uploads. But it is not clear that some APIs ought to take in a name.

I do hesitate to merge in this PR as it is, since we would be baking in a default behaviour that is different from the other SDKs. I will go and convene with my colleagues to ensure a consistent default behaviour across SDKs first 👍 .

Thank you so much for taking note of this!

**Comment by dan-jensen** [comment]
> I do hesitate to merge in this PR as it is, since we would be baking in a default behaviour that is different from the other SDKs.

@ms-jpq actually, this SDK is the one that's different. Your other SDKs must already be including `filename`, otherwise they would produce this error as well.

For clarity, the first 2 of the 3 documented usage examples ALWAYS produce this error:

```
# Use `Pathname` to send the filename and/or avoid paging a large file into memory:
file_metadata = anthropic.beta.files.upload(file: Pathname("/path/to/file"))

# Alternatively, pass file contents or a `StringIO` directly:
file_metadata = anthropic.beta.files.upload(file: File.read("/path/to/file"))
```

Neither of those include a `filename` so they cause Anthropic's Starlette instance to return the error.

If your other SDKs are not triggering this error then they must be including `filename` to the `Content-Disposition` part header. Most multipart clients do, like cURL, and like this SDK would if it used the [multipart-post gem](https://rubygems.org/gems/multipart-post). The problem is this particular gem generates multipart content from scratch using custom code that deviates from convention. This PR simply brings the `Content-Disposition` part header in line with convention. In other words, this PR aligns this SDK with your other SDKs.

**Comment by ms-jpq** [comment]
ok will finally have some breather to get to this tomorrow .😞

i appreciate the patience, there are some other exciting things coming at some point in the future, so i have been de-prioritizing this, since its not a strict blocker for SDK usage.

**Comment by dan-jensen** [comment]
@ms-jpq sounds great. I just took a second pass and simplified the code. Hopefully an easy review because this just expands an existing feature.

**Comment by ms-jpq** [comment]
hey @dan-jensen , when I read the RFC, as it turns out:

https://datatracker.ietf.org/doc/html/rfc7578#section-4.2

```
   For form data that represents the content of a file, a name for the
   file SHOULD be supplied as well, by using a "filename" parameter of
   the Content-Disposition header field.  The file name isn't mandatory
   for cases where the file name isn't available or is meaningless or
   private; this might result, for example, when selection or drag-and-
   drop is used or when the form data content is streamed directly from
   a device.
```

so I am a bit torn. while the python SDK does provide a `file` as the filename by default. so we could potentially just use that.

---

I am inclined to just document the usage of https://gemdocs.org/gems/anthropic/1.9.0/Anthropic/FilePart.html

in the README as a solution.

i.e. something like

```
content = File.read("<some path>")

client.beta.files.upload(AnthropicFilePart::new(content, filename: "my file"))
```

File: test/anthropic/internal/util_test.rb [hunk 1]
```diff
@@ -228,7 +228,7 @@ def test_file_encode
       encoded = Anthropic::Internal::Util.encode_content(headers, body)
       cgi = FakeCGI.new(*encoded)
       assert_pattern do
-        cgi[""].read => ^val
```
Comment (ms-jpq) [inline test/anthropic/internal/util_test.rb:231]: this is actually introduces a bug haha, `^val` means "assert `val` === `value`", while `=>  val` just assigns `cgi[""].read` to `val`

Comment (dan-jensen) [reply test/anthropic/internal/util_test.rb:231]: Ugh, what a tricky syntax. Just pushed a commit to restore the pinned variables 👍

**Comment by dan-jensen** [comment]
> as it turns out [filename is recommended in RFC]

@ms-jpq yep, recommended in RFC but _required_ by web server interfaces _including yours_ (Starlette). That's why this PR ensures it is always given. That's the bugfix.

> so I am a bit torn

Torn about what, the default name? That's unimportant, I just changed it to "file" to match the Python SDK.

> I am inclined to just document the usage

Why document a workaround to a bug instead of fixing the bug? At this point that would be _more_ work than fixing the bug, because you can fix the bug by clicking "merge".

Here's my perspective: You rolled your own multipart builder and it deviates from multipart standards. This PR brings your builder in line with standards. That's why you're finding your other SDKs already behave this way. **Can we merge this PR to fix this SDK and bring it in line with your other SDKs?**

**Comment by ms-jpq** [comment]
hi @dan-jensen, 

I modified the tests to assert against the filename input, and will merge this.

thank you for stumping on this issue, I had been hesitant to do something that is not exactly RFC compliant, but you have made it obvious that this is the correct decision.

---

for what it's worth, rolling our own HTTP stack is due to the need of supporting enumeration based streaming, and the requirement for the SDK to have minimal dependencies

File: lib/anthropic/internal/util.rb [hunk 2]
```diff
@@ -537,23 +537,26 @@ class << self
         # @param closing [Array<Proc>]
         private def write_multipart_chunk(y, boundary:, key:, val:, closing:)
           y << "--#{boundary}\r\n"
-          y << "Content-Disposition: form-data"
+          y << "Content-Disposition: form-data;"
 
           unless key.nil?
```
Comment (ms-jpq) [inline lib/anthropic/internal/util.rb:542]: @dan-jensen FYI, i reverted to this `key.nil?` condition. in the Anthropic API, providing a non-matching key is always the wrong thing to do.

if we provided the wrong key, the API will return an error that should say something like "you provided a unexpected `file` parameter". which is not the error that we want.

Comment (dan-jensen) [reply lib/anthropic/internal/util.rb:542]: > i reverted to this key.nil? condition

@ms-jpq whoops, looks like that introduced a bug. The semi-colon in line 544 must be moved to the end, otherwise the header is malformed.

> providing a non-matching key is always the wrong thing to do

I don't understand what you mean by "non-matching". The key/name value seems to be 1) arbitrary and 2) not validated by the Anthropic API. But let's stop discussing `name` in this PR.

Because `name` is required by RFC and you seem to care about RFC, I assumed you'd want it. Although I still think it's advisable, I understand you reverting it. It's not the bugfix and it has become a distraction, so let's focus on `filename` because that's the bugfix.

Comment (ms-jpq) [reply lib/anthropic/internal/util.rb:542]: https://github.com/anthropics/anthropic-sdk-ruby/commit/0ffb017c542b98891c6fcee76d7e3f3cb7ae5f26

I added an alternative fix ! :D

Comment (dan-jensen) [reply lib/anthropic/internal/util.rb:542]: @ms-jpq unfortunately that doesn't fix the bug for all cases. If you modify `Util#write_multipart_chunk` to raise an exception if `filename` is not given, you'll see your test suite raises at least 2 exceptions. First, this suggests you should add that exception permanently, otherwise the bug is only mitigated but not prevented. Second, this suggests the simpler solution was better.

Bigger picture: I'm surprised you reverted this PR, because that's a big deal. I'm also surprised you committed something else without asking for another perspective. I wish we could have collaborated and reached a better outcome. This whole experience has been quite discouraging to me as a community contributor 😞

Comment (ms-jpq) [reply lib/anthropic/internal/util.rb:542]: hi @dan-jensen.

I understand your frustration. I failed to get back to your issues in a speedy manner, and I did not adequately explain my decisions for the final approach taken.

Not going to excuse myself for those two failings, but please understand that the motivation was not because that I did not appreciate your contributions. We have been absolutely slammed with work, so up-streaming contributions has taken a back seat, and expositions for our design decisions even more so.

I had actually been dreading the disappointment, and I am genuinely remorseful that I did not do the due diligence for a conversation on the whys the design choice was taken.

---

the TLDR for why the SDK has shipped deliberately with it's own encoder / decoder & HTTP stack is actually fairly simple:

1. we did not want to deal with potential version conflicts in the set of external dependencies

2. we needed to support streaming as a first class citizen, for both upload and download, so you can have the best possible latency and resource usage.

---

the other design constraint is that we deliberately follow that maxim that "we only transform the users' input in so far as it is well specified by the expected API specification" otherwise as always pass the user's input verbatim with minimal processing.

this mostly has to do with

1) when the API evolves, you should still be able to use an old SDK and just specify the "unexpected" properties, and nothing in the library should make this unnecessarily difficult 

2) power users should always be able to specify whatever they desire, without the library enforcing any additional behaviours.

Comment (dan-jensen) [reply lib/anthropic/internal/util.rb:542]: @ms-jpq I understand wanting to pass the user's input verbatim with minimal processing. That's perfectly reasonable, but it doesn't respond to my comment. I said the bug remains and an exception should be added.

To elaborate on that: The error "Part exceeded maximum size of 1024KB" is not a helpful way of explaining "You need to specify a `filename`." If this gem isn't going to automatically solve the problem like other multipart builders, it should at least flag the problem and explain how to solve it. That's what the exception would do.
